In [6]:
import pandas as pd
import numpy as np

In [24]:
data = pd.read_csv("/Shikhar/GPT-Accuracy-Research/youtube_gpt_video_data.csv")
data

,Video Title,View Count,Like Count,Dislike Count,Comments
0,ChatGPT Explained Completely.,930749,53531,0,Thanks for watching! This is a deeper dive tha...
1,ChatGPT Explained Completely.,930749,53531,0,Linguistics is fascinating. I was fortunate to...
2,ChatGPT Explained Completely.,930749,53531,0,"So, what is the mind&#39;s so-called &#39;inte..."
3,ChatGPT Explained Completely.,930749,53531,0,Intersring how many layers the chatgpt neural ...
4,ChatGPT Explained Completely.,930749,53531,0,I guess we have now a huge library of question...
...,...,...,...,...,...
247572,"창의력을 길러주는 환경을 '이렇게' 만드세요 / 챗GPT, 영어공부에 활용하는 법/...",3240,89,0,피부에 와닿는 좋은 말씀 인상 깊어요<br>저희 아이는 2학년때 마인크래프트 게임을...
247573,ΕΧΕΙ ΞΕΚΙΝΗΣΕΙ Η ΕΠΟΧΗ ΤΗΣ ΜΕΓΑΛΗΣ ΣΥΓΧΥΣΗΣ ...,443,81,0,ΚΑΛΗΣΠΕΡΑ ΑΓΑΠΗΤΕ ΜΟΥ<br> ΑΛΕΞ.....<br>Ε...
247574,ΕΧΕΙ ΞΕΚΙΝΗΣΕΙ Η ΕΠΟΧΗ ΤΗΣ ΜΕΓΑΛΗΣ ΣΥΓΧΥΣΗΣ ...,443,81,0,Πατερ Νικόλαος Λουδοβίκος αυτός είναι ένας μορ...
247575,ΕΧΕΙ ΞΕΚΙΝΗΣΕΙ Η ΕΠΟΧΗ ΤΗΣ ΜΕΓΑΛΗΣ ΣΥΓΧΥΣΗΣ ...,443,81,0,Καλησπέρα Αλέξανδρε!
247576,ΕΧΕΙ ΞΕΚΙΝΗΣΕΙ Η ΕΠΟΧΗ ΤΗΣ ΜΕΓΑΛΗΣ ΣΥΓΧΥΣΗΣ ...,443,81,0,Καλησπέρα σας<br>Ει ο Θεός μεθ Ημών ουδείς καθ...

In [25]:
data.head()

,Video Title,View Count,Like Count,Dislike Count,Comments
0,ChatGPT Explained Completely.,930749,53531,0,Thanks for watching! This is a deeper dive tha...
1,ChatGPT Explained Completely.,930749,53531,0,Linguistics is fascinating. I was fortunate to...
2,ChatGPT Explained Completely.,930749,53531,0,"So, what is the mind&#39;s so-called &#39;inte..."
3,ChatGPT Explained Completely.,930749,53531,0,Intersring how many layers the chatgpt neural ...
4,ChatGPT Explained Completely.,930749,53531,0,I guess we have now a huge library of question...

In [27]:
data.describe()

         View Count     Like Count  Dislike Count
count  2.475770e+05  247577.000000       247577.0
mean   1.654927e+06   50922.818020            0.0
std    1.470245e+06   50292.923113            0.0
min    2.100000e+01       0.000000            0.0
25%    4.509190e+05   14293.000000            0.0
50%    1.168964e+06   40578.000000            0.0
75%    2.508140e+06   82360.000000            0.0
max    5.571243e+06  381840.000000            0.0

In [28]:
data.describe(include=[np.object])

C:\Users\Raj Vardhan Tomar\AppData\Local\Temp\ipykernel_4548\1422700444.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data.describe(include=[np.object])

                                              Video Title Comments
count                                              247577   247574
unique                                                500   219830
top     I Asked AI about the Second Coming of Jesus, a...     100%
freq                                                16894      366

In [23]:
df=pd.concat(map(pd.read_csv, ["/Shikhar/GPT-Accuracy-Research/reddit_gpt_comments.csv", "/Shikhar/GPT-Accuracy-Research/reddit_gpt_comments1.csv", "/Shikhar/GPT-Accuracy-Research/reddit_gpt_comments2.csv"]), ignore_index=True)
df.describe()
df.to_csv("/Shikhar/GPT-Accuracy-Research/reddit_gpt_data.csv")